name: Build and Push Docker Image

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  DOCKERHUB_USERNAME: cloudbeesdemo
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Get version
      id: version
      run: echo "VERSION=$(python scripts/get-version.py)" >> $GITHUB_OUTPUT
      
    - name: Replace commit SHA placeholder
      run: |
        sed -i 's/COMMIT_SHA_PLACEHOLDER/${{ github.sha }}/g' templates/base.html
      
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: ${{ github.event_name != 'pull_request' }}
        tags: |
          ${{ env.DOCKERHUB_USERNAME }}/mimic:latest
          ${{ env.DOCKERHUB_USERNAME }}/mimic:${{ steps.version.outputs.VERSION }}
        cache-from: type=gha
        cache-to: type=gha,mode=max